# WebSocket输出组件
[GoPLWebSocketServerOutput]
  disabled = true
  topic = "*"
[GoPLWebSocketServerOutput.InitArgs]
  conn_handshake_timeout = "10s"
  conn_write_timeout = "10s"
  path_uri = "/ws"
  server_max_clients = 64
  session_cache_size = 10
  auth_check_origin = true
  auth_origins = [
    "127.0.0.1"
  ]


# Kafka 输出组件
[GoPLKafkaProducerOutput]
  disabled = true
  topic = "*"
[GoPLKafkaProducerOutput.InitArgs]
  message_key = "test-data"
  message_topic = "go-pipeline-test"
  brokers = [
    "192.168.1.15:9092",
    "192.168.1.25:9092",
  ]